// Package assetpack builds the archive of assets/extracted that the executables carry inside
// them, and checks a built one against the tree it was built from.
//
// # Why an archive and not a directory of //go:embed patterns
//
// Three of the twenty-two 1994 houses have an apostrophe in their name -- "Castle o' the Air",
// "Nemo's Market" and "Rainbow's End" -- and so do the three directories of art extracted from
// their resource forks: 120 files in all. go:embed refuses any file whose name is not a valid
// **module file path**, and that rule forbids the apostrophe along with the other shell
// metacharacters. Naming such a file in a pattern fails the build:
//
//	pattern extracted/houses/*.house: cannot embed file extracted/houses/Castle o' the Air.house:
//	invalid name Castle o' the Air.house
//
// and -- much worse -- naming its *directory* instead does not fail. A directory pattern
// silently skips every entry with a name it cannot package, so `//go:embed extracted/houses`
// would have produced a game that was missing three houses and said nothing about it.
//
// Renaming the files was the other way out and is not taken. A house has no name of its own:
// houseType has no name field, because on a Mac the document was named by its file, so the
// file name **is** the house name -- it is what the picker lists, what the high-score side-car
// is keyed on and what the player types after -house. Encoding it would put a rule between the
// 1994 name and every one of those, forever, to work around a restriction that only ever
// applied to one packaging format. A zip entry name has no such restriction, so the bytes go in
// a zip and the names stay exactly as John Calhoun wrote them in 1994.
//
// # What this costs
//
// The archive is a second copy of bytes that are already committed, about 11 MiB of it. It is
// generated by `make assets-zip` from the tree beside it and the assets package's own test
// compares the two file by file, so the copy cannot drift; docs/IMPROVEMENTS.md 5.3 records the
// alternative -- keep only the archive and unpack on demand -- and why it was not taken yet.
package assetpack

import (
	"archive/zip"
	"bytes"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// Name is the archive's file name, inside the assets package's own directory so that go:embed
// can name it -- a pattern cannot reach outside the package it is written in.
const Name = "extracted.zip"

// packTime is the timestamp every entry gets.
//
// One fixed value, and not the file's own mtime, so that two packs of the same tree produce the
// same archive: a checkout's mtimes are whenever git wrote them, which would make the committed
// archive change every time anybody regenerated it. The date is the month Glider PRO 1.1.2
// shipped, which is as true of these bytes as any other date would be false.
var packTime = time.Date(1994, time.October, 1, 0, 0, 0, 0, time.UTC)

// Skip reports whether one path relative to the tree root stays out of the archive.
//
// The rules are .gitignore's, for its reasons. houses/*.rsrc are the per-house resource forks
// tools/extract_house_art.py decodes into houseart/: 24 MB of extractor input that nothing
// reads at run time and that is deliberately not committed either. Dotfiles and __pycache__ are
// whatever a tool or an operating system left in the tree and are not part of the extraction.
func Skip(rel string) bool {
	if strings.HasSuffix(rel, ".rsrc") {
		return true
	}
	for _, elem := range strings.Split(rel, "/") {
		if elem == "__pycache__" || strings.HasPrefix(elem, ".") {
			return true
		}
	}
	return false
}

// Files lists the tree's packable files, as slash-separated paths relative to dir, sorted.
//
// Sorted because the order decides the archive's bytes and an archive that depends on the order
// a file system happened to hand its directories over is one that changes for no reason.
func Files(dir string) ([]string, error) {
	var names []string
	err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(dir, path)
		if err != nil {
			return err
		}
		rel = filepath.ToSlash(rel)
		if rel == "." {
			return nil
		}
		if Skip(rel) {
			if d.IsDir() {
				return fs.SkipDir
			}
			return nil
		}
		if d.IsDir() {
			return nil
		}
		if !d.Type().IsRegular() {
			// A symlink or a device node in an asset tree is somebody's mistake, and
			// copying what it points at into the archive would hide it.
			return fmt.Errorf("assetpack: %s is not a regular file", rel)
		}
		names = append(names, rel)
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Strings(names)
	return names, nil
}

// Create writes the archive of dir to w.
//
// Every entry is deflated. The art is PNG and the sound is compressed already, so most of the
// tree does not shrink -- but the houses, the resource forks and the manifests do, and the
// executable ends up smaller than it would have been carrying the files raw.
func Create(w io.Writer, dir string) error {
	names, err := Files(dir)
	if err != nil {
		return err
	}
	if len(names) == 0 {
		return fmt.Errorf("assetpack: %s holds no assets", dir)
	}

	zw := zip.NewWriter(w)
	for _, name := range names {
		b, err := os.ReadFile(filepath.Join(dir, filepath.FromSlash(name)))
		if err != nil {
			return err
		}
		// No mode bits and no directory entries. The zip's fs.FS synthesises the
		// directories, and a mode would only record the umask of whoever ran the pack.
		f, err := zw.CreateHeader(&zip.FileHeader{
			Name:     name,
			Method:   zip.Deflate,
			Modified: packTime,
		})
		if err != nil {
			return err
		}
		if _, err := f.Write(b); err != nil {
			return err
		}
	}
	return zw.Close()
}

// CreateFile writes the archive to a path, via a temporary file and a rename so that an
// interrupted pack cannot leave a truncated archive where the good one was -- which would be an
// archive that still builds and is missing assets.
func CreateFile(path, dir string) error {
	tmp, err := os.CreateTemp(filepath.Dir(path), ".assetpack-*")
	if err != nil {
		return err
	}
	name := tmp.Name()
	defer os.Remove(name) // a no-op once the rename has succeeded
	if err := Create(tmp, dir); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Chmod(name, 0o644); err != nil {
		return err
	}
	return os.Rename(name, path)
}

// Open reads an archive from bytes as a filesystem. This is what the assets package hands the
// game, and it is what Compare reads.
func Open(b []byte) (fs.FS, error) {
	return zip.NewReader(bytes.NewReader(b), int64(len(b)))
}

// Compare reports every way an archive's contents differ from a tree's: a file in one and not
// the other, or one whose bytes do not match.
//
// It compares contents and not the archive's own bytes, because two archives of the same tree
// are not required to be byte-identical -- the deflate stream is whatever the toolchain's
// compressor produced, and a Go upgrade may change it. What has to hold is that the executable
// is carrying the files that are committed, and that is what this answers.
//
// The result is at most limit lines, so a test can print it without burying its own message.
func Compare(fsys fs.FS, dir string, limit int) ([]string, error) {
	want, err := Files(dir)
	if err != nil {
		return nil, err
	}

	var diffs []string
	add := func(format string, args ...any) {
		if len(diffs) < limit {
			diffs = append(diffs, fmt.Sprintf(format, args...))
		}
	}

	inArchive := make(map[string]bool)
	err = fs.WalkDir(fsys, ".", func(name string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() {
			inArchive[name] = true
		}
		return nil
	})
	if err != nil {
		return nil, err
	}

	for _, name := range want {
		if !inArchive[name] {
			add("%s: in the tree, not in the archive", name)
			continue
		}
		delete(inArchive, name)
		onDisk, err := os.ReadFile(filepath.Join(dir, filepath.FromSlash(name)))
		if err != nil {
			return nil, err
		}
		packed, err := fs.ReadFile(fsys, name)
		if err != nil {
			return nil, err
		}
		if !bytes.Equal(onDisk, packed) {
			add("%s: %d bytes in the tree, %d in the archive", name, len(onDisk), len(packed))
		}
	}

	extra := make([]string, 0, len(inArchive))
	for name := range inArchive {
		extra = append(extra, name)
	}
	sort.Strings(extra)
	for _, name := range extra {
		add("%s: in the archive, not in the tree", name)
	}
	return diffs, nil
}
